### ISSUE TITLE
Gemfile cleanup

### ISSUE THREAD

**Issue by olivierobert** [shirishkz/nimble-scraper-app#1]
Always remove un-used gems:

![gemfile_-_shirish_-___volumes_workspace__candidates-tests_shirish_](https://user-images.githubusercontent.com/696529/31646178-7f6be702-b32a-11e7-9866-5a177141ae6a.png)

In addition, for discoverability purposes, move the ruby version at the top of the Gemfile:

![gemfile_-_shirish_-___volumes_workspace__candidates-tests_shirish_](https://user-images.githubusercontent.com/696529/31646207-accb933c-b32a-11e7-95f5-4d66cae4de18.png)

**Comment by shirishkz** [comment]
Noted, already fixed.
